# Automations
automation: !include_dir_merge_list automations/

# Binary sensors
binary_sensor: !include misc/binary_sensors.yaml

# Climate
climate: !include misc/climate.yaml

# Enables configuration UI
config:

# Rollershutters
cover: !include misc/cover.yaml

# Discover some devices automatically
discovery:

# Emulated Hue Hub
emulated_hue:
  host_ip: !secret hue_host

# Enables energy module
energy:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Groups
group: !include groups.yaml

# History
history:

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: AUD
  time_zone: !secret home_time_zone
  customize: !include customize.yaml
# Allowlist for writing files
  allowlist_external_dirs:
    - '/config/tmp'
  allowlist_external_urls:
    - 'http://192.168.1.4:5000/api/events'
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url
  auth_mfa_modules:
   - type: totp
#  auth_providers:
#   - type: trusted_networks
#     trusted_networks: 
#      - !secret home_network

http:
  # Uncomment this to add a password (recommended!)
  # api_password: 
  # Uncomment this if you are using SSL or running in Docker etc
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.160.0/24
    - 192.168.96.0/24
    - 172.16.0.0/12
    - 127.0.0.1
    - ::1 

#InfluxDB

influxdb:
  host: !secret influx_host
  include:
    entities:
      - sensor.wupws_temp
      - sensor.sensebender_micro_4_1
      - sensor.sensebender_micro_5_1
      - sensor.sensebender_micro_6_1
      - sensor.sensebender_micro_7_1
      - sensor.sensebender_micro_8_1
      - sensor.solar_generation
      - sensor.power_use

# Input booleans
input_boolean: !include misc/input_booleans.yaml

# Input numbers
input_number: !include misc/input_numbers.yaml

# Input selects
input_select: !include misc/input_selects.yaml

# Voice assistant intents
intent:

# iOS integration
ios: !include misc/ios.yaml

# Lighting
light: !include_dir_merge_list lights/

# View all events in a logbook
logbook:

# Disable some error logging
logger:
   default: error

# Enable media source
media_source:

# Home Assistant Companion
mobile_app:

# Mosquitto
mqtt:
  discovery: true
  broker: !secret mqtt_host
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

# MySensors
mysensors:
  gateways:
    - device: mqtt
      persistence_file: '/config/mysensors.json'
      topic_in_prefix: 'mygateway1-out'
      topic_out_prefix: 'mygateway1-in'
  optimistic: false
  persistence: true
  retain: true
  version: 2.0

# Notifications
notify:
  - name: mpfl
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# updater:

# Owntracks
owntracks:

# Enables support for tracking state changes over time.
recorder:
  # Delete events and states older than 2 weeks
  purge_keep_days: 7

roomba:
  - host: !secret roomba_host
    blid: !secret roomba_blid
    password: !secret roomba_pw

# Scripts
script: !include_dir_named scripts/

# Track the sun
sun:

# Switches
switch: !include_dir_merge_list switches/

# Enables support for tracking state changes over time.
system_health:

# Text-to-speech
tts:
  - platform: google_translate

# Sensors
sensor: !include_dir_merge_list sensors

# smartIR climate control

smartir:

# Timers
# Zigbee2MQTT Timer for joining time remaining (120 sec = 2 min)
timer: !include misc/timers.yaml

# Weather
weather: !include misc/weather.yaml

# Zones
zone:
  - name: Home
    latitude: !secret home_latitude 
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple

# Connection for LG OLED TV
webostv:
  host: !secret home_theatre_tv_host
  name: Home Theatre TV
