- platform: wundergroundpws
  api_key: !secret wunderground_api_key
  pws_id: !secret wunderground_pws_id
  numeric_precision: none
  monitored_conditions:
    - humidity
    - temp
    - temp_high_1d
    - weather_1d

